apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: system-storage
  labels:
    app: 3scale-api-management
    threescale_component: system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "100Mi"
  storageClassName: gp2
  volumeMode: Filesystem
